project:
  type: website

website:
  title: "Medha Khanal"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Marketing Analytics"
        href: marketing-analytics.qmd
      - text: "Strategic Marketing"
        href: strategic-marketing.qmd
      - text: "Résumé"
        href: resume.qmd
      - text: "Dashboard"
        href: dashboard.qmd
      - text: "Presentation"
        href: presentation.qmd
      - text: "Analytics"
        href: analytics.qmd



format:
  html:
    theme: [flatly, theme.scss]
    toc: true
    include-in-header: includes/gtm-head.html      # Injects GTM script into <head>
    include-before-body: includes/gtm-body.html    # Injects GTM noscript immediately after <body> opens

